version: '2'
services:

  nginx:
    image: nginx:1.13-alpine
    depends_on:
      - fpm
    ports:
      - "80:80"
    volumes:
      - "$PWD/etc/env/dev/nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "$PWD/src/UI/API/public/index.php:/app/src/UI/API/public/index.php"

  fpm:
    image: jorge07/alpine-php:7.1-dev-sf
    ports:
      - "2323:22"
      - "9000:9000"
    volumes:
      - "$PWD:/app"