parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Leos\UI\API\Controller\:
        resource: '../src/UI/API/Controller'
        tags: ['controller.service_arguments']

    Leos\Application\:
        resource: '../src/Application/**/*Handler'
        tags: ['bus.handler']

    Leos\UI\API\EventListener\ExceptionListener:
        tags:
          - { name: kernel.event_listener, event: kernel.exception }
